--Some global constants for game.

-- size of our actual window
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

-- size we're trying to emulate with push
VIRTUAL_WIDTH = 1280
VIRTUAL_HEIGHT = 720

VIRUS_SPEED_X = 100
VIRUS_SPEED_Y = 200
VIRUS_ROT_SPEED = 2
VIRUS_SCALE = 0.5

--the number of viruses on the atlas
TOTAL_VIRUSES = 42

--initial characteristics on the wave 1
INITIAL_LIFES = 3
INITIAL_VIRUS_COUNT = 5
INITIAL_VIRUS_SPEED_COEF = 1.0
INITIAL_COUNT_BOT_CELLS = 0

CELL_SPEED = 300

COLLISION_DISTANCE_0 = 40
COLLISION_DISTANCE_1 = 50
COLLISION_DISTANCE_2 = 60
COLLISION_DISTANCE_3 = 80

LEVEL_UP_1 = 10
LEVEL_UP_2 = 15
LEVEL_UP_3 = 25


